### ISSUE TITLE
File path error when attempting `rx init --remote=...`

### ISSUE THREAD

**Issue by dcrosta** [run-rx/getting-started#1]
I was following (approximately) the instructions in the 04-remote-config.py script, and got this error:

```
(rx-getting-started@master) dcrosta@botfly.local:~/src/rx-getting-started ± cat .rx/remotes/py-310
{
  "image": {
    "docker": "python:3.10"
  }
}
(rx-getting-started@master) dcrosta@botfly.local:~/src/rx-getting-started ± rx init --remote=py-310
Looks like you already have an rx workspace. Would you like to stop that one
and start a new one? (Y/n): y
Got it. To re-init this workspace, rx will:

1. Shut down your existing virtual machine.
2. Set up a virtual machine on the cloud (on AWS).
3. Copy over the files in this directory (/Users/dcrosta/Dropbox/src/rx-getting-started) to your
   virtual machine.

Would you like to proceed? (Y/n): y
Traceback (most recent call last):
  File "/Users/dcrosta/.pyenv/versions/rx-getting-started/bin/rx", line 8, in <module>
    sys.exit(run())
             ^^^^^
  File "/Users/dcrosta/.pyenv/versions/3.11.1/envs/rx-getting-started/lib/python3.11/site-packages/rx/client/commands/exec.py", line 105, in run
    app.run(main)
  File "/Users/dcrosta/.pyenv/versions/3.11.1/envs/rx-getting-started/lib/python3.11/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/Users/dcrosta/.pyenv/versions/3.11.1/envs/rx-getting-started/lib/python3.11/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
             ^^^^^^^^^^
  File "/Users/dcrosta/.pyenv/versions/3.11.1/envs/rx-getting-started/lib/python3.11/site-packages/rx/client/commands/exec.py", line 99, in main
    return cmd.run()
           ^^^^^^^^^
  File "/Users/dcrosta/.pyenv/versions/3.11.1/envs/rx-getting-started/lib/python3.11/site-packages/rx/client/commands/init.py", line 78, in run
    config = local.create_local_config(self._rxroot)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dcrosta/.pyenv/versions/3.11.1/envs/rx-getting-started/lib/python3.11/site-packages/rx/client/configuration/local.py", line 127, in create_local_config
    c.setup_remote()
  File "/Users/dcrosta/.pyenv/versions/3.11.1/envs/rx-getting-started/lib/python3.11/site-packages/rx/client/configuration/local.py", line 43, in setup_remote
    with remote_path.open(mode='rt', encoding='utf-8') as fh:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dcrosta/.pyenv/versions/3.11.1/lib/python3.11/pathlib.py", line 1044, in open
    return io.open(self, mode, buffering, encoding, errors, newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/Users/dcrosta/Dropbox/src/rx-getting-started/py-310'
```

I believe the error is here: https://github.com/run-rx/rx/blob/master/rx/client/configuration/local.py#L41

I think that line should be `remote_path = _REMOTE_DIR / remote` or similar

**Comment by kchodorow** [comment]
Thanks for the report! It used to be, but I changed it so you can put config files anywhere. Updated the example.
